# Generated by Django 2.2.3 on 2019-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(max_length=2),
        ),
    ]
