# Generated by Django 2.2.3 on 2019-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20190716_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
