# Generated by Django 2.2.3 on 2019-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20190716_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
